version: '3.8'

services:
  pgdatabase:
    image: postgres:13
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: greentaxi
    volumes:
      - ../data/greentaxidata:/var/lib/postgresql/data
    ports:
      - 5431:5432
    networks:
      - greentaxi-network
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 8080:80
    networks:
      - greentaxi-network

networks:
  greentaxi-network:
    driver: bridge
